### ISSUE TITLE
switch julia environment by setting `Base.ACTIVE_PROJECT` fast than `Pkg.activate()`

### ISSUE THREAD

**Issue by songjhaha** [Suzhou-Tongyuan/jnumpy#28]
`Pkg.activate()` costs more in io and other things, we could just set `Base.ACTIVE_PROJECT`.

**Comment by thautwarm** [comment]
Does this have any compatibility concerns? Is it stable?

**Comment by songjhaha** [comment]
No significant improvement compared to `Pkg.activate()`  when loading python package, so let's keep original version.
