### ISSUE TITLE
py_cast(::Type{Tuple}, ::Py) should not work like py_coerce

### ISSUE THREAD

**Issue by songjhaha** [Suzhou-Tongyuan/jnumpy#32]
https://github.com/Suzhou-Tongyuan/jnumpy/blob/11793535a08232e71817eabacd25849661924b81/TyPython/src/CPython.ORM.jl#L270-L272

**Comment by thautwarm** [comment]
This could mean that casting is now deeply covariant for immutable types, or such covariant rule is special for tuples. I prefer the latter. Implicit conversions are hard to maintain at the developer side.
