### ISSUE TITLE
Wrapping Julia errors with a RuntimeError might be too general

### ISSUE THREAD

**Issue by thautwarm** [Suzhou-Tongyuan/jnumpy#48]
https://github.com/Suzhou-Tongyuan/jnumpy/blob/65cea6cc6a750911ab2c1545d94af26008e7b240/TyPython/src/CPython.Dev.jl#L102

**Comment by songjhaha** [comment]
Handle some cases of julia errors? like:

|  Julia | Python  |
|:-----:|:----:|
| `MethodError`  | `TypeError`|
| `BoundsError` | `IndexError`|
| `KeyError` | `KeyError` |
