### ISSUE TITLE
suppress errors in the fast loading path

### ISSUE THREAD

**Issue by thautwarm** [Suzhou-Tongyuan/jnumpy#55]
we might call `redirect_stderr` at https://github.com/Suzhou-Tongyuan/jnumpy/blob/65cea6cc6a750911ab2c1545d94af26008e7b240/jnumpy/init.py#L172

**Comment by songjhaha** [comment]
It seems error message comes from:
https://github.com/Suzhou-Tongyuan/jnumpy/blob/1d7e2007abb10fcc29cb4efb0e190c4829bd40f6/jnumpy/apis.py#L87-L89

`use_gil=False` should not print out error.

**Comment by songjhaha** [comment]
done by #58
