### ISSUE TITLE
1.9 support

### ISSUE THREAD

**Issue by xgdgsc** [Suzhou-Tongyuan/jnumpy#78]
Thanks for the package. Hope 1.9 support can be added.

**Comment by songjhaha** [comment]
After removing the version check in https://github.com/Suzhou-Tongyuan/jnumpy/blob/67471561813bb9d0acd78cf157521789f7b0c62a/jnumpy/InitTools.jl#L8, jnumpy could work in my windows os with julia 1.9.1, I would run more tests to make sure everything is working properly then update the repo.

**Comment by songjhaha** [comment]
solved with #81
